language: go

go:
- 1.12.x
- 1.13.x

before_install:
  - go mod download

notifications:
    on_success: never
    on_failure: always

script:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on GOSUMDB=off go build -o cachego main.go