dist: trusty
language: go
go_import_path: src/hunter32292.github.com/cache2go 
sudo: false

go:
  - 1.8

notifications:
    on_success: never
    on_failure: never


before_install:
    - go get -v -u github.com/gorilla/mux

script:
    - go build -o cache2go src/hunter32292.github.com/cache2go/*.go 
